/**
 * Created by Ruben on 29-03-2016.
 */
function NetCode() {}
NetCode.USUARIO_LOGIN_OK = 0;
NetCode.USUARIO_LOGIN_INACTIVO = 1;
NetCode.USUARIO_LOGIN_NOEXISTE = 2;

NetCode.TAQUILLA_LOGIN_OK = 10;
NetCode.TAQUILLA_LOGIN_INACTIVO = 11;
NetCode.TAQUILLA_LOGIN_NOEXISTE = 12;
NetCode.TAQUILLA_VENTA_OK = 13;
NetCode.TAQUILLA_VENTA_RECHAZADA = 14;